crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/',include('notes.urls')),
]

notes/urls.py
from django.urls import path
from .import views

app_name = "notes"

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add_note, name="add"),
    path('delete/<int:note_id>/', views.delete_note, name="delete"),
]

notes/models.py
from django.db import models


class Note(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

notes/forms.py
from django import forms
from .models import Note


class NoteForm(forms.Form):
    title = forms.CharField(
        max_length=100,
        error_messages={'required': "Title is required"}
    )
    description = forms.CharField(
        widget=forms.Textarea(),
        error_messages={'required': "Description is required"}
    )

    def clean_description(self):
        description = self.cleaned_data.get('description', '')
        if len(description) < 10:
            raise forms.ValidationError(
                'Description must be at least 10 characters long.')
        return description

    def create(self, validated_data):
        return Note.objects.create(**validated_data)

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Note
from .forms import NoteForm


def index(request):
    notes = Note.objects.all().order_by('-id')
    return render(request, 'notes/index.html', {
        'notes': notes})


def add_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            form.create(form.cleaned_data)
            messages.success(request, "Note added successfully!")
            return redirect('notes:index')
    else:
        form = NoteForm()

    return render(request, "notes/add.html", {
        'form': form
    })


def delete_note(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    note.delete()
    messages.success(request, "Note deleted successfully!")
    return redirect('notes:index')

notes/templates/notes/add.html
{% extends 'notes/base.html' %}
{% block title %}
    Add Notes
{% endblock title %}
{% block content %}
    <form action="{% url 'notes:add' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit" name="submit">
    </form>
{% endblock content %}

notes/templates/notes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
                Notes App
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'notes/style.css' %}">
    </head>
    <body>
        {% include 'notes/partials/header.html' %}
        {% if messages %}
            {% for message in messages %}<p class="{{ message.tags }}">{{ message }}</p>{% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
    </body>
</html>

notes/templates/notes/index.html
{% extends "notes/base.html" %}
{% block content %}
    <h3>Notes List</h3>
    <table>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
        {% for n in notes %}
            <tr>
                <td>{{ n.title }}</td>
                <td>{{ n.description }}</td>
                <td>
                    <a href="#">Edit</a>
                    |
                    <a href="{% url 'notes:delete' n.id %}"
                       onclick="return confirm('Are you sure to delete?')">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

notes/templates/notes/partials/header.html
<nav>
    <a href="{% url 'notes:index' %}">Home</a>
    |
    <a href="/notes/add">Add Note</a>
</nav>
<br>
<br>